=begin
Dkron REST API

You can communicate with Dkron using a RESTful JSON API over HTTP. Dkron nodes usually listen on port `8080` for API requests. All examples in this section assume that you've found a running leader at `localhost:8080`.\n\nDkron implements a RESTful JSON API over HTTP to communicate with software clients. Dkron listens in port `8080` by default. All examples in this section assume that you're using the default port.\n\nDefault API responses are unformatted JSON add the `pretty=true` param to format the response.\n

OpenAPI spec version: 0.7.2

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for Dkron::JobsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @instance = Dkron::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instact of JobsApi' do
      @instance.should be_a(Dkron::JobsApi)
    end
  end

  # unit tests for create_or_update_job
  # 
  # Create or updates a new job.\n
  # @param body Updated job object
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'create_or_update_job test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for delete_job
  # 
  # Delete a job.\n
  # @param job_name The job that needs to be deleted.
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'delete_job test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_jobs
  # 
  # List jobs.\n
  # @param [Hash] opts the optional parameters
  # @return [Array<Job>]
  describe 'get_jobs test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for run_job
  # 
  # Executes a job.\n
  # @param job_name The job that needs to be run.
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'run_job test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for show_job_by_name
  # 
  # Show a job.\n
  # @param job_name The job that needs to be fetched.
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'show_job_by_name test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
